/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as privatePlayersRouteRouteImport } from './routes/(private)/players/route'
import { Route as publicSignUpIndexRouteImport } from './routes/(public)/sign-up/index'
import { Route as publicSignInIndexRouteImport } from './routes/(public)/sign-in/index'
import { Route as privatePlayersIndexRouteImport } from './routes/(private)/players/index'
import { Route as privateClansIndexRouteImport } from './routes/(private)/clans/index'
import { Route as privateAdminIndexRouteImport } from './routes/(private)/admin/index'
import { Route as privatePushClanTagRouteImport } from './routes/(private)/push/$clanTag'
import { Route as privatePlayersPlayerTagRouteImport } from './routes/(private)/players/$playerTag'
import { Route as privateClanClanTagRouteRouteImport } from './routes/(private)/clan/$clanTag/route'
import { Route as privateClanClanTagIndexRouteImport } from './routes/(private)/clan/$clanTag/index'
import { Route as privateClanClanTagNormalRouteImport } from './routes/(private)/clan/$clanTag/normal'
import { Route as privateClanClanTagHistoryRouteImport } from './routes/(private)/clan/$clanTag/history'
import { Route as privateClanClanTagCwlRouteImport } from './routes/(private)/clan/$clanTag/cwl'
import { Route as privateClanClanTagCurrentRouteImport } from './routes/(private)/clan/$clanTag/current'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const privatePlayersRouteRoute = privatePlayersRouteRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicSignUpIndexRoute = publicSignUpIndexRouteImport.update({
  id: '/(public)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInIndexRoute = publicSignInIndexRouteImport.update({
  id: '/(public)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePlayersIndexRoute = privatePlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privatePlayersRouteRoute,
} as any)
const privateClansIndexRoute = privateClansIndexRouteImport.update({
  id: '/clans/',
  path: '/clans/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateAdminIndexRoute = privateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePushClanTagRoute = privatePushClanTagRouteImport.update({
  id: '/push/$clanTag',
  path: '/push/$clanTag',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePlayersPlayerTagRoute = privatePlayersPlayerTagRouteImport.update({
  id: '/$playerTag',
  path: '/$playerTag',
  getParentRoute: () => privatePlayersRouteRoute,
} as any)
const privateClanClanTagRouteRoute = privateClanClanTagRouteRouteImport.update({
  id: '/clan/$clanTag',
  path: '/clan/$clanTag',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateClanClanTagIndexRoute = privateClanClanTagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateClanClanTagRouteRoute,
} as any)
const privateClanClanTagNormalRoute =
  privateClanClanTagNormalRouteImport.update({
    id: '/normal',
    path: '/normal',
    getParentRoute: () => privateClanClanTagRouteRoute,
  } as any)
const privateClanClanTagHistoryRoute =
  privateClanClanTagHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => privateClanClanTagRouteRoute,
  } as any)
const privateClanClanTagCwlRoute = privateClanClanTagCwlRouteImport.update({
  id: '/cwl',
  path: '/cwl',
  getParentRoute: () => privateClanClanTagRouteRoute,
} as any)
const privateClanClanTagCurrentRoute =
  privateClanClanTagCurrentRouteImport.update({
    id: '/current',
    path: '/current',
    getParentRoute: () => privateClanClanTagRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/players': typeof privatePlayersRouteRouteWithChildren
  '/': typeof homeIndexRoute
  '/clan/$clanTag': typeof privateClanClanTagRouteRouteWithChildren
  '/players/$playerTag': typeof privatePlayersPlayerTagRoute
  '/push/$clanTag': typeof privatePushClanTagRoute
  '/admin/': typeof privateAdminIndexRoute
  '/clans/': typeof privateClansIndexRoute
  '/players/': typeof privatePlayersIndexRoute
  '/sign-in/': typeof publicSignInIndexRoute
  '/sign-up/': typeof publicSignUpIndexRoute
  '/clan/$clanTag/current': typeof privateClanClanTagCurrentRoute
  '/clan/$clanTag/cwl': typeof privateClanClanTagCwlRoute
  '/clan/$clanTag/history': typeof privateClanClanTagHistoryRoute
  '/clan/$clanTag/normal': typeof privateClanClanTagNormalRoute
  '/clan/$clanTag/': typeof privateClanClanTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/players/$playerTag': typeof privatePlayersPlayerTagRoute
  '/push/$clanTag': typeof privatePushClanTagRoute
  '/admin': typeof privateAdminIndexRoute
  '/clans': typeof privateClansIndexRoute
  '/players': typeof privatePlayersIndexRoute
  '/sign-in': typeof publicSignInIndexRoute
  '/sign-up': typeof publicSignUpIndexRoute
  '/clan/$clanTag/current': typeof privateClanClanTagCurrentRoute
  '/clan/$clanTag/cwl': typeof privateClanClanTagCwlRoute
  '/clan/$clanTag/history': typeof privateClanClanTagHistoryRoute
  '/clan/$clanTag/normal': typeof privateClanClanTagNormalRoute
  '/clan/$clanTag': typeof privateClanClanTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/players': typeof privatePlayersRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(private)/clan/$clanTag': typeof privateClanClanTagRouteRouteWithChildren
  '/(private)/players/$playerTag': typeof privatePlayersPlayerTagRoute
  '/(private)/push/$clanTag': typeof privatePushClanTagRoute
  '/(private)/admin/': typeof privateAdminIndexRoute
  '/(private)/clans/': typeof privateClansIndexRoute
  '/(private)/players/': typeof privatePlayersIndexRoute
  '/(public)/sign-in/': typeof publicSignInIndexRoute
  '/(public)/sign-up/': typeof publicSignUpIndexRoute
  '/(private)/clan/$clanTag/current': typeof privateClanClanTagCurrentRoute
  '/(private)/clan/$clanTag/cwl': typeof privateClanClanTagCwlRoute
  '/(private)/clan/$clanTag/history': typeof privateClanClanTagHistoryRoute
  '/(private)/clan/$clanTag/normal': typeof privateClanClanTagNormalRoute
  '/(private)/clan/$clanTag/': typeof privateClanClanTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/players'
    | '/'
    | '/clan/$clanTag'
    | '/players/$playerTag'
    | '/push/$clanTag'
    | '/admin/'
    | '/clans/'
    | '/players/'
    | '/sign-in/'
    | '/sign-up/'
    | '/clan/$clanTag/current'
    | '/clan/$clanTag/cwl'
    | '/clan/$clanTag/history'
    | '/clan/$clanTag/normal'
    | '/clan/$clanTag/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/players/$playerTag'
    | '/push/$clanTag'
    | '/admin'
    | '/clans'
    | '/players'
    | '/sign-in'
    | '/sign-up'
    | '/clan/$clanTag/current'
    | '/clan/$clanTag/cwl'
    | '/clan/$clanTag/history'
    | '/clan/$clanTag/normal'
    | '/clan/$clanTag'
  id:
    | '__root__'
    | '/(home)'
    | '/(private)'
    | '/(private)/players'
    | '/(home)/'
    | '/(private)/clan/$clanTag'
    | '/(private)/players/$playerTag'
    | '/(private)/push/$clanTag'
    | '/(private)/admin/'
    | '/(private)/clans/'
    | '/(private)/players/'
    | '/(public)/sign-in/'
    | '/(public)/sign-up/'
    | '/(private)/clan/$clanTag/current'
    | '/(private)/clan/$clanTag/cwl'
    | '/(private)/clan/$clanTag/history'
    | '/(private)/clan/$clanTag/normal'
    | '/(private)/clan/$clanTag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicSignInIndexRoute: typeof publicSignInIndexRoute
  publicSignUpIndexRoute: typeof publicSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(private)/players': {
      id: '/(private)/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof privatePlayersRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/sign-up/': {
      id: '/(public)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof publicSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in/': {
      id: '/(public)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof publicSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/players/': {
      id: '/(private)/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof privatePlayersIndexRouteImport
      parentRoute: typeof privatePlayersRouteRoute
    }
    '/(private)/clans/': {
      id: '/(private)/clans/'
      path: '/clans'
      fullPath: '/clans/'
      preLoaderRoute: typeof privateClansIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/admin/': {
      id: '/(private)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof privateAdminIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/push/$clanTag': {
      id: '/(private)/push/$clanTag'
      path: '/push/$clanTag'
      fullPath: '/push/$clanTag'
      preLoaderRoute: typeof privatePushClanTagRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/players/$playerTag': {
      id: '/(private)/players/$playerTag'
      path: '/$playerTag'
      fullPath: '/players/$playerTag'
      preLoaderRoute: typeof privatePlayersPlayerTagRouteImport
      parentRoute: typeof privatePlayersRouteRoute
    }
    '/(private)/clan/$clanTag': {
      id: '/(private)/clan/$clanTag'
      path: '/clan/$clanTag'
      fullPath: '/clan/$clanTag'
      preLoaderRoute: typeof privateClanClanTagRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/clan/$clanTag/': {
      id: '/(private)/clan/$clanTag/'
      path: '/'
      fullPath: '/clan/$clanTag/'
      preLoaderRoute: typeof privateClanClanTagIndexRouteImport
      parentRoute: typeof privateClanClanTagRouteRoute
    }
    '/(private)/clan/$clanTag/normal': {
      id: '/(private)/clan/$clanTag/normal'
      path: '/normal'
      fullPath: '/clan/$clanTag/normal'
      preLoaderRoute: typeof privateClanClanTagNormalRouteImport
      parentRoute: typeof privateClanClanTagRouteRoute
    }
    '/(private)/clan/$clanTag/history': {
      id: '/(private)/clan/$clanTag/history'
      path: '/history'
      fullPath: '/clan/$clanTag/history'
      preLoaderRoute: typeof privateClanClanTagHistoryRouteImport
      parentRoute: typeof privateClanClanTagRouteRoute
    }
    '/(private)/clan/$clanTag/cwl': {
      id: '/(private)/clan/$clanTag/cwl'
      path: '/cwl'
      fullPath: '/clan/$clanTag/cwl'
      preLoaderRoute: typeof privateClanClanTagCwlRouteImport
      parentRoute: typeof privateClanClanTagRouteRoute
    }
    '/(private)/clan/$clanTag/current': {
      id: '/(private)/clan/$clanTag/current'
      path: '/current'
      fullPath: '/clan/$clanTag/current'
      preLoaderRoute: typeof privateClanClanTagCurrentRouteImport
      parentRoute: typeof privateClanClanTagRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface privatePlayersRouteRouteChildren {
  privatePlayersPlayerTagRoute: typeof privatePlayersPlayerTagRoute
  privatePlayersIndexRoute: typeof privatePlayersIndexRoute
}

const privatePlayersRouteRouteChildren: privatePlayersRouteRouteChildren = {
  privatePlayersPlayerTagRoute: privatePlayersPlayerTagRoute,
  privatePlayersIndexRoute: privatePlayersIndexRoute,
}

const privatePlayersRouteRouteWithChildren =
  privatePlayersRouteRoute._addFileChildren(privatePlayersRouteRouteChildren)

interface privateClanClanTagRouteRouteChildren {
  privateClanClanTagCurrentRoute: typeof privateClanClanTagCurrentRoute
  privateClanClanTagCwlRoute: typeof privateClanClanTagCwlRoute
  privateClanClanTagHistoryRoute: typeof privateClanClanTagHistoryRoute
  privateClanClanTagNormalRoute: typeof privateClanClanTagNormalRoute
  privateClanClanTagIndexRoute: typeof privateClanClanTagIndexRoute
}

const privateClanClanTagRouteRouteChildren: privateClanClanTagRouteRouteChildren =
  {
    privateClanClanTagCurrentRoute: privateClanClanTagCurrentRoute,
    privateClanClanTagCwlRoute: privateClanClanTagCwlRoute,
    privateClanClanTagHistoryRoute: privateClanClanTagHistoryRoute,
    privateClanClanTagNormalRoute: privateClanClanTagNormalRoute,
    privateClanClanTagIndexRoute: privateClanClanTagIndexRoute,
  }

const privateClanClanTagRouteRouteWithChildren =
  privateClanClanTagRouteRoute._addFileChildren(
    privateClanClanTagRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privatePlayersRouteRoute: typeof privatePlayersRouteRouteWithChildren
  privateClanClanTagRouteRoute: typeof privateClanClanTagRouteRouteWithChildren
  privatePushClanTagRoute: typeof privatePushClanTagRoute
  privateAdminIndexRoute: typeof privateAdminIndexRoute
  privateClansIndexRoute: typeof privateClansIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatePlayersRouteRoute: privatePlayersRouteRouteWithChildren,
  privateClanClanTagRouteRoute: privateClanClanTagRouteRouteWithChildren,
  privatePushClanTagRoute: privatePushClanTagRoute,
  privateAdminIndexRoute: privateAdminIndexRoute,
  privateClansIndexRoute: privateClansIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicSignInIndexRoute: publicSignInIndexRoute,
  publicSignUpIndexRoute: publicSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
