/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as privatePlayersRouteRouteImport } from './routes/(private)/players/route'
import { Route as publicSignUpIndexRouteImport } from './routes/(public)/sign-up/index'
import { Route as publicSignInIndexRouteImport } from './routes/(public)/sign-in/index'
import { Route as privatePlayersIndexRouteImport } from './routes/(private)/players/index'
import { Route as privateClansIndexRouteImport } from './routes/(private)/clans/index'
import { Route as privateAdminIndexRouteImport } from './routes/(private)/admin/index'
import { Route as privateWarsClanTagRouteImport } from './routes/(private)/wars/$clanTag'
import { Route as privatePushClanTagRouteImport } from './routes/(private)/push/$clanTag'
import { Route as privatePlayersPlayerTagRouteImport } from './routes/(private)/players/$playerTag'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const privatePlayersRouteRoute = privatePlayersRouteRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicSignUpIndexRoute = publicSignUpIndexRouteImport.update({
  id: '/(public)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInIndexRoute = publicSignInIndexRouteImport.update({
  id: '/(public)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePlayersIndexRoute = privatePlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privatePlayersRouteRoute,
} as any)
const privateClansIndexRoute = privateClansIndexRouteImport.update({
  id: '/clans/',
  path: '/clans/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateAdminIndexRoute = privateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateWarsClanTagRoute = privateWarsClanTagRouteImport.update({
  id: '/wars/$clanTag',
  path: '/wars/$clanTag',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePushClanTagRoute = privatePushClanTagRouteImport.update({
  id: '/push/$clanTag',
  path: '/push/$clanTag',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePlayersPlayerTagRoute = privatePlayersPlayerTagRouteImport.update({
  id: '/$playerTag',
  path: '/$playerTag',
  getParentRoute: () => privatePlayersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/players': typeof privatePlayersRouteRouteWithChildren
  '/': typeof homeIndexRoute
  '/players/$playerTag': typeof privatePlayersPlayerTagRoute
  '/push/$clanTag': typeof privatePushClanTagRoute
  '/wars/$clanTag': typeof privateWarsClanTagRoute
  '/admin': typeof privateAdminIndexRoute
  '/clans': typeof privateClansIndexRoute
  '/players/': typeof privatePlayersIndexRoute
  '/sign-in': typeof publicSignInIndexRoute
  '/sign-up': typeof publicSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/players/$playerTag': typeof privatePlayersPlayerTagRoute
  '/push/$clanTag': typeof privatePushClanTagRoute
  '/wars/$clanTag': typeof privateWarsClanTagRoute
  '/admin': typeof privateAdminIndexRoute
  '/clans': typeof privateClansIndexRoute
  '/players': typeof privatePlayersIndexRoute
  '/sign-in': typeof publicSignInIndexRoute
  '/sign-up': typeof publicSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/players': typeof privatePlayersRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(private)/players/$playerTag': typeof privatePlayersPlayerTagRoute
  '/(private)/push/$clanTag': typeof privatePushClanTagRoute
  '/(private)/wars/$clanTag': typeof privateWarsClanTagRoute
  '/(private)/admin/': typeof privateAdminIndexRoute
  '/(private)/clans/': typeof privateClansIndexRoute
  '/(private)/players/': typeof privatePlayersIndexRoute
  '/(public)/sign-in/': typeof publicSignInIndexRoute
  '/(public)/sign-up/': typeof publicSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/players'
    | '/'
    | '/players/$playerTag'
    | '/push/$clanTag'
    | '/wars/$clanTag'
    | '/admin'
    | '/clans'
    | '/players/'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/players/$playerTag'
    | '/push/$clanTag'
    | '/wars/$clanTag'
    | '/admin'
    | '/clans'
    | '/players'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/(home)'
    | '/(private)'
    | '/(private)/players'
    | '/(home)/'
    | '/(private)/players/$playerTag'
    | '/(private)/push/$clanTag'
    | '/(private)/wars/$clanTag'
    | '/(private)/admin/'
    | '/(private)/clans/'
    | '/(private)/players/'
    | '/(public)/sign-in/'
    | '/(public)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicSignInIndexRoute: typeof publicSignInIndexRoute
  publicSignUpIndexRoute: typeof publicSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(private)/players': {
      id: '/(private)/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof privatePlayersRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/sign-up/': {
      id: '/(public)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in/': {
      id: '/(public)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/players/': {
      id: '/(private)/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof privatePlayersIndexRouteImport
      parentRoute: typeof privatePlayersRouteRoute
    }
    '/(private)/clans/': {
      id: '/(private)/clans/'
      path: '/clans'
      fullPath: '/clans'
      preLoaderRoute: typeof privateClansIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/admin/': {
      id: '/(private)/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof privateAdminIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/wars/$clanTag': {
      id: '/(private)/wars/$clanTag'
      path: '/wars/$clanTag'
      fullPath: '/wars/$clanTag'
      preLoaderRoute: typeof privateWarsClanTagRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/push/$clanTag': {
      id: '/(private)/push/$clanTag'
      path: '/push/$clanTag'
      fullPath: '/push/$clanTag'
      preLoaderRoute: typeof privatePushClanTagRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/players/$playerTag': {
      id: '/(private)/players/$playerTag'
      path: '/$playerTag'
      fullPath: '/players/$playerTag'
      preLoaderRoute: typeof privatePlayersPlayerTagRouteImport
      parentRoute: typeof privatePlayersRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface privatePlayersRouteRouteChildren {
  privatePlayersPlayerTagRoute: typeof privatePlayersPlayerTagRoute
  privatePlayersIndexRoute: typeof privatePlayersIndexRoute
}

const privatePlayersRouteRouteChildren: privatePlayersRouteRouteChildren = {
  privatePlayersPlayerTagRoute: privatePlayersPlayerTagRoute,
  privatePlayersIndexRoute: privatePlayersIndexRoute,
}

const privatePlayersRouteRouteWithChildren =
  privatePlayersRouteRoute._addFileChildren(privatePlayersRouteRouteChildren)

interface privateRouteRouteChildren {
  privatePlayersRouteRoute: typeof privatePlayersRouteRouteWithChildren
  privatePushClanTagRoute: typeof privatePushClanTagRoute
  privateWarsClanTagRoute: typeof privateWarsClanTagRoute
  privateAdminIndexRoute: typeof privateAdminIndexRoute
  privateClansIndexRoute: typeof privateClansIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatePlayersRouteRoute: privatePlayersRouteRouteWithChildren,
  privatePushClanTagRoute: privatePushClanTagRoute,
  privateWarsClanTagRoute: privateWarsClanTagRoute,
  privateAdminIndexRoute: privateAdminIndexRoute,
  privateClansIndexRoute: privateClansIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicSignInIndexRoute: publicSignInIndexRoute,
  publicSignUpIndexRoute: publicSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
